# Generated by Django 4.1.2 on 2022-11-29 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_remove_order_description_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, verbose_name=('Completed',)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=('Created',)),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name=('Active',)),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False, help_text=('Means the oder has been cancelled.',), verbose_name=('Archived',)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=('Updated',)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=('Created',)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=('Updated',)),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=('Created',)),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=('Updated',)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=('Updated',)),
        ),
    ]
