# Generated by Django 4.1.2 on 2022-11-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='null', upload_to='Users/Customers/profile_pictures/%Y/%m/'),
        ),
    ]
